name: Debug Close Issue on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  debug-close-issue:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Fetch PR Body
      - name: Fetch PR Body
        id: fetch_pr_body
        run: |
          echo "Fetching PR Body..."
          RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.CONFIG_SUBMODULE_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}")
          echo "API Response:"
          echo "$RESPONSE"
          PR_BODY=$(echo "$RESPONSE" | jq -r '.body')
          echo "Extracted PR Body:"
          echo "$PR_BODY"
          echo "PR_BODY=$PR_BODY" >> $GITHUB_ENV

      # Step 3: Extract issue number
      - name: Extract issue number
        id: extract_issue
        run: |
          echo "Extracting issue number from PR Body..."
          echo "PR Body: ${{ env.PR_BODY }}"
          ISSUE_NUMBER=$(echo "${{ env.PR_BODY }}" | grep -oP '#\d+' | head -1 | sed 's/#//')
          echo "Extracted Issue Number: $ISSUE_NUMBER"
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV

      # Step 4: Log extracted issue number
      - name: Log issue number
        run: |
          echo "Final extracted issue number is: ${{ env.ISSUE_NUMBER }}"

      # Step 5: Attempt to close the associated issue (only if ISSUE_NUMBER is not empty)
      - name: Close associated issue
        if: ${{ env.ISSUE_NUMBER && env.ISSUE_NUMBER != '' }}
        run: |
          echo "Attempting to close issue #${{ env.ISSUE_NUMBER }}"
          curl -s -X PATCH -H "Authorization: token ${{ secrets.CONFIG_SUBMODULE_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"state": "closed"}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ env.ISSUE_NUMBER }}"
